package au.com.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'royh' at '19/05/17 2:40 PM' with Gradle 2.5
 *
 * @author royh, @date 19/05/17 2:40 PM
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
