package au.com.sportsbet;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'royh' at '19/05/17 2:40 PM' with Gradle 2.5
 *
 * @author royh, @date 19/05/17 2:40 PM
 */
@RunWith(SpringRunner.class)
@SpringBootTest
public class ApplicationTest {

    @Test
    public void exampleTest() {
      assertTrue(true);
    }

}

